### ISSUE TITLE
Updating for 2022

### ISSUE THREAD

**Issue by ChadDa3mon** [ernesen/infra-ansible#3]
Greetings,

I came across your [article on medium.com](https://medium.com/design-and-tech-co/end-to-end-automated-environment-with-vagrant-ansible-docker-jenkins-and-gitlab-32bb91fbee40) and loved what you had, I was so excited to fire this up and check things out as I'm trying to learn Ansible, Vagrant, and Jenkins for my new job. I was sad to see I had similar issues to the other users who have posted issues. 

I understand people get busy and you may not be able or willing to update this. I'd like to help as I could stand to learn a good deal from this project, but I'm a bit too novice to make heads or tails of things. If you wouldn't mind giving me some pointers to help get me started, I'd appreciate it. If I can get this working, I'll submit a PR so this can get updated. 

The issue I have is the same as [this issue](https://github.com/ernesen/infra-ansible/issues/1). I'm running on MacOS Monterey with Vagrant 2.2.19. If I can get past this issue, then I can work on what @n00b78 suggested in their [issue](https://github.com/ernesen/infra-ansible/issues/2). 

```
  <snip>
    ansible.sample.com: [jenkins]
    ansible.sample.com: jenkins.sample.com
    ansible.sample.com:
    ansible.sample.com: [docker]
    ansible.sample.com: docker.sample.com
    ansible.sample.com:
    ansible.sample.com: [gitlab]
    ansible.sample.com: gitlab.sample.com
    ansible.sample.com: dos2unix: /home/vagrant/artefacts/scripts/ssh_pass.sh: No such file or directory
    ansible.sample.com: dos2unix: Skipping /home/vagrant/artefacts/scripts/ssh_pass.sh, not a regular file.
    ansible.sample.com: chmod: cannot access ‘/home/vagrant/artefacts/scripts/ssh_pass.sh’: No such file or directory
    ansible.sample.com: /tmp/vagrant-shell: 117: /tmp/vagrant-shell: /home/vagrant/artefacts/scripts/ssh_pass.sh: not found
    ansible.sample.com: /tmp/vagrant-shell: 119: /tmp/vagrant-shell: /home/vagrant/artefacts/scripts/ssh_pass.sh: not found
    ansible.sample.com: /tmp/vagrant-shell: 121: /tmp/vagrant-shell: /home/vagrant/artefacts/scripts/ssh_pass.sh: not found
    ansible.sample.com: /tmp/vagrant-shell: 123: /tmp/vagrant-shell: /home/vagrant/artefacts/scripts/ssh_pass.sh: not found
    ansible.sample.com: /tmp/vagrant-shell: 125: /tmp/vagrant-shell: /home/vagrant/artefacts/scripts/ssh_pass.sh: not found
    ansible.sample.com: /tmp/vagrant-shell: 127: /tmp/vagrant-shell: /home/vagrant/artefacts/scripts/ssh_pass.sh: not found
    ansible.sample.com: ERROR! the playbook: /home/vagrant/artefacts/playbooks/nfs_server.yaml could not be found
    ansible.sample.com: ERROR! the playbook: /home/vagrant/artefacts/playbooks/nfs_clients.yaml could not be found
    ansible.sample.com: ERROR! the playbook: /home/vagrant/artefacts/playbooks/install_java.yaml could not be found
    ansible.sample.com: ERROR! the playbook: /home/vagrant/artefacts/playbooks/install_jenkins.yaml could not be found
    ansible.sample.com: ERROR! the playbook: /home/vagrant/artefacts/playbooks/install_docker.yaml could not be found
    ansible.sample.com: ERROR! the playbook: /home/vagrant/artefacts/playbooks/install_gitlab.yaml could not be found
```
I assume the vagrant file is trying (or should be trying) to execute the dos2unix commands on the ansible host we created, but it is failing. I'm not sure how your script knows to execute these on the host. I assume maybe something has changed with how Vagrant handles things since the version you used when you first wrote this. 

Any help you can give would be greatly appreciated. Even if you don't have the time (and I understand if you don't) thanks for taking the time to write your article and set this up.
